### ISSUE TITLE
Why the locks?

### ISSUE THREAD

**Issue by singpolyma** [tinychameleon/uuidx#1]
I'm curious why you chose to use a pool of entropy state with locks around it here rather than calling `SecureRandom` during generation?

**Comment by unsrtified** [comment]
👋🏻 It's a good question. Some of the answer is historical and may not be valid anymore. I haven't benchmarked again in awhile.

---

I was benchmarking throughput of the new UUID versions against the standard `SecureRandom.uuid` and needed to hit higher throughput numbers. The pool of bytes from `SecureRandom.bytes` had an faster amortized runtime than hitting the cryptographically secure randomization source every call.

The locks around the top-level `Uuidx.vX` methods are there because those simple APIs wrap a single generator. If that generator is used from multiple threads, there are theoretical order of operations that could yield the same UUID based on the shared generator state. For example, 2 calls to a v6 generator could theoretically get the same 100ns resolution timestamp and generate the same clock sequence if context switched around the compound assignment.

So, I basically decided to push the locks out to the simple API and allow manual construction of each generator for anyone that wants 1 per thread or whatever other use-case there might be.
